//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coacching_Center_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class exam
    {
        public int Id { get; set; }
        public string examcode { get; set; }
        public string time { get; set; }
        public int qno { get; set; }
        public string question { get; set; }
        public string optiona { get; set; }
        public string optionb { get; set; }
        public string optionc { get; set; }
        public string optiond { get; set; }
        public string correctoption { get; set; }
    }
}
