//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coacching_Center_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class examinfo
    {
        public int Id { get; set; }
        public string examcode { get; set; }
        public Nullable<int> time { get; set; }
        public string numofques { get; set; }
    }
}
