//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coacching_Center_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_info
    {
        public long id { get; set; }
        public string userid { get; set; }
        public string name { get; set; }
        public string courcode { get; set; }
        public string examcode { get; set; }
        public Nullable<int> qno { get; set; }
        public string attpt { get; set; }
        public string selectedoption { get; set; }
        public string correctornot { get; set; }
        public Nullable<int> marks { get; set; }
    }
}
